// twitter-emulation-spring-boot-angular-web/src/app/not-found.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-not-found',
  templateUrl: './not-found.component.html'
})
export class NotFoundComponent implements OnInit {
  constructor() {
  }

  ngOnInit() {
  }
}

<div>
  <h3 class="bg-info p-1 text-white">Page not found</h3>
</div>

// twitter-emulation-spring-boot-react-web/src/unknown/NotFoundComponent.tsx
import { Component } from 'react';
import { Link } from 'react-router';

export default class NotFoundComponent extends Component {
    render() {
        return (
            <div className="container-dialog p-2">
                <h3 className="bg-info p-1 text-white text-center rounded">Page not found</h3>

                <div className="text-center">
                    Go to <Link to="/account/show">Main page</Link>
                </div>
            </div>
        );
    }
}
