// twitter-emulation-spring-boot-angular-web/src/app/modules/home/account-info.component.ts
import { Component, Input } from '@angular/core';
import { Router } from '@angular/router';
import { UserState } from '../../shared/models/user-state.model';
import { AccountStatistics } from "../../shared/models/account-statistics.model";
import { FollowerService } from "../../shared/services/follower.service";

@Component({
  selector: 'app-account-info',
  templateUrl: './account-info.component.html'
})
export class AccountInfoComponent {
  @Input('userState')
  userState: UserState;

  @Input('accountStatistics')
  accountStatistics: AccountStatistics;

  constructor(private followerService: FollowerService, private router: Router) {
  }

  follow() {
    this.followerService.follow(this.userState.selectedUserName)
      .subscribe(data => {
        this.router.navigate(['/account', 'show', this.userState.selectedUserName]);
      });
  }

  unfollow() {
    this.followerService.unfollow(this.userState.selectedUserName)
      .subscribe(data => {
        this.router.navigate(['/account', 'show', this.userState.selectedUserName]);
      });
  }

  isFollowVisible(): boolean {
    return this.userState.isAuthenticated() && (this.userState.authenticatedUserName !== this.userState.selectedUserName);
  }
}

<div class="card p-3 bg-light">
  <div class="row">
    <div class="col">
      <div class="row fw-bold">
        <div class="col-12" id="description">{{accountStatistics.description}}</div>
      </div>
      <div class="row">
        <div class="col-12" id="username">&#64;{{accountStatistics.username}}</div>
      </div>
    </div>
    <div *ngIf="isFollowVisible()" class="col-auto" id="buttons">
      <button *ngIf="!accountStatistics.follow" class="btn btn-primary m-0" (click)="follow()" id="follow">Follow</button>
      <button *ngIf="accountStatistics.follow" class="btn btn-primary m-0" (click)="unfollow()" id="unfollow">Unfollow</button>
    </div>
  </div>
  <div class="row mt-1">
    <div class="col-4 small">
      <a class="fw-bold" [routerLink]="['/account', 'tweets', accountStatistics.username]">Tweets</a>
    </div>
    <div class="col-4 small">
      <a class="fw-bold" [routerLink]="['/account', 'following', accountStatistics.username]">Following</a>
    </div>
    <div class="col-4 small">
      <a class="fw-bold" [routerLink]="['/account', 'followers', accountStatistics.username]">Followers</a>
    </div>
  </div>
  <div class="row">
    <div class="col-4 small">
      <a class="fw-bold" id="tweets" [routerLink]="['/account', 'tweets', accountStatistics.username]">{{accountStatistics.tweetsCount}}</a>
    </div>
    <div class="col-4 small">
      <a class="fw-bold" id="following" [routerLink]="['/account', 'following', accountStatistics.username]">{{accountStatistics.followingCount}}</a>
    </div>
    <div class="col-4 small">
      <a class="fw-bold" id="followers" [routerLink]="['/account', 'followers', accountStatistics.username]">{{accountStatistics.followersCount}}</a>
    </div>
  </div>
</div>

// twitter-emulation-spring-boot-react-web/src/home/AccountInfo.tsx
import { Component } from 'react';
import { Link } from 'react-router-dom';
import { resolve } from 'inversify-react';
import { AccountStatistics } from '../common/models/AccountStatistics';
import { UserState } from '../common/models/UserState';
import { AccountService } from '../common/services/AccountService';
import { FollowerService } from '../common/services/FollowerService';

type AccountInfoProps = {
    userState: UserState;
};

type AccountInfoState = {
    accountStatistics: AccountStatistics;
};

export default class AccountInfo extends Component<AccountInfoProps, AccountInfoState> {
    @resolve(AccountService)
    private readonly accountService!: AccountService;

    @resolve(FollowerService)
    private readonly followerService!: FollowerService;

    constructor(props: AccountInfoProps) {
        super(props);

        this.state = {
            accountStatistics: new AccountStatistics()
        };
    }

    loadAccountStatistics() {
        const username = this.props.userState.getDataUserName();

        if (username) {
            this.accountService.getAccountStatistics(username)
                .subscribe(data => {
                        this.setState({
                            accountStatistics: data
                        });
                    }
                );
        }
    }

    componentDidMount() {
        this.loadAccountStatistics();
    }

    follow = () => {
        if (this.props.userState.selectedUserName) {
            this.followerService.follow(this.props.userState.selectedUserName)
                .subscribe(data => {
                        this.loadAccountStatistics();
                    }
                );
        }
    }

    unfollow = () => {
        if (this.props.userState.selectedUserName) {
            this.followerService.unfollow(this.props.userState.selectedUserName)
                .subscribe(data => {
                        this.loadAccountStatistics();
                    }
                );
        }
    }

    isFollowVisible(): boolean {
        return this.props.userState.isAuthenticated() && (this.props.userState.authenticatedUserName !== this.props.userState.selectedUserName);
    }

    render() {
        return (
            <div className="card p-3 bg-light">
                <div className="row">
                    <div className="col">
                        <div className="row fw-bold">
                            <div className="col-12" data-testid="description">{this.state.accountStatistics.description}</div>
                        </div>
                        <div className="row">
                            <div className="col-12" data-testid="username">@{this.state.accountStatistics.username}</div>
                        </div>
                    </div>
                    {this.isFollowVisible() &&
                        <div className="col-auto" data-testid="buttons">
                            {
                                this.state.accountStatistics.follow ?
                                    <button className="btn btn-primary m-0" onClick={this.unfollow} data-testid="unfollow">Unfollow</button> :
                                    <button className="btn btn-primary m-0" onClick={this.follow} data-testid="follow">Follow</button>
                            }
                        </div>
                    }
                </div>
                <div className="row mt-1">
                    <div className="col-4 small">
                        <Link to={`/account/tweets/${this.state.accountStatistics.username}`} className="fw-bold">
                            Tweets
                        </Link>
                    </div>
                    <div className="col-4 small">
                        <Link to={`/account/following/${this.state.accountStatistics.username}`} className="fw-bold">
                            Following
                        </Link>
                    </div>
                    <div className="col-4 small">
                        <Link to={`/account/followers/${this.state.accountStatistics.username}`} className="fw-bold">
                            Followers
                        </Link>
                    </div>
                </div>
                <div className="row">
                    <div className="col-4 small">
                        <Link to={`/account/tweets/${this.state.accountStatistics.username}`} className="fw-bold">
                            {this.state.accountStatistics.tweetsCount}
                        </Link>
                    </div>
                    <div className="col-4 small">
                        <Link to={`/account/following/${this.state.accountStatistics.username}`} className="fw-bold">
                            {this.state.accountStatistics.followingCount}
                        </Link>
                    </div>
                    <div className="col-4 small">
                        <Link to={`/account/followers/${this.state.accountStatistics.username}`} className="fw-bold">
                            {this.state.accountStatistics.followersCount}
                        </Link>
                    </div>
                </div>
            </div>
        );
    }
}
