// twitter-emulation-spring-boot-angular-web/src/app/home/account.component.ts
import { Component, OnInit } from '@angular/core';
import { Tweet } from "../tweet";
import { TweetService } from "../tweet.service";

@Component({
  selector: 'app-account',
  templateUrl: './account.component.html'
})
export class AccountComponent implements OnInit {
  private tweets: Tweet[] = [
    new Tweet('John Doe', 'jdoe', 'Some people care too much. I think it\'s called love.', new Date()),
    new Tweet('John Smith', 'jsmith', 'Lorem ipsum dolor sit amet, impetus iuvaret in nam. Inani tritani fierent ut vix, vim ut dolore animal. Nisl noster fabellas sed ei.', new Date()),
    new Tweet('John Doe', 'jdoe', 'You can\'t stay in your corner of the Forest waiting for others to come to you. You have to go to them sometimes.', new Date()),
    new Tweet('John Smith', 'jsmith', 'Duo suas molestiae ea, ex sit rebum voluptua. Graeci mandamus ad mei, harum rationibus qui at. Ut vel fabellas deserunt senserit.', new Date()),
    new Tweet('John Doe', 'jdoe', 'It is more fun to talk with someone who doesn\'t use long, difficult words but rather short, easy words like "What about lunch?"', new Date()),
    new Tweet('John Smith', 'jsmith', 'Vel eros vero cu, at vis animal ceteros. Veritus invidunt postulant qui ne. Mel latine patrioque necessitatibus id, ius ne adhuc maluisset.', new Date()),
    new Tweet('John Smith', 'jsmith', 'No per viderer invidunt consequat, vix ei probo oratio luptatum, quo stet graece an. Has in nemore partiendo.', new Date()),
    new Tweet('John Smith', 'jsmith', 'Decore ocurreret te vis, eligendi scaevola no vel. Brute hendrerit duo ne. Molestie percipitur adversarium quo ut.', new Date()),
    new Tweet('John Smith', 'jsmith', 'At nobis voluptaria sed, quo at eius laudem gloriatur, ne sapientem salutandi pro. Erat quaeque electram vim at.', new Date()),
  ];

  constructor(private tweet: TweetService) {
  }

  ngOnInit() {
  }
}

<div class="container p-0">
  <app-top-bar></app-top-bar>
  <div class="row text-black m-0">
    <div class="col-3 p-1">
      <app-account-info></app-account-info>
    </div>
    <div class="col-6 p-1">
      <div *ngFor="let tweet of tweets" class="card m-0 p-1 bg-light">
        <h6>
          <a class="font-weight-bold" href="#">{{tweet.username}}</a> @{{tweet.description}}
          <span class="badge badge-pill badge-primary float-right">
            {{tweet.date | date:"dd.MM.yyyy hh:mm:ss"}}
          </span>
        </h6>
        <div class="card-text bg-white p-1">{{tweet.text}}</div>
      </div>
    </div>
    <div class="col-3 p-1">
      <app-follow></app-follow>
    </div>
  </div>
</div>

// twitter-emulation-spring-boot-react-web/src/home/Account.tsx
import { Component } from 'react';
import Home from "./Home";
import Tweets from './Tweets';
import { Tweet } from '../common/Tweet';

type AccountProps = {};

type AccountState = {
    tweets: Tweet[];
};

export default class Account extends Component<AccountProps, AccountState> {
    constructor(props: AccountProps) {
        super(props);

        // TODO: change
        this.state = {
            tweets: [
                new Tweet(
                    'jdoe',
                    'John Doe',
                    'Some people care too much. I think it\'s called love.',
                    new Date('2022-04-21T19:36:01')),
                new Tweet(
                    'jsmith',
                    'John Smith',
                    'Lorem ipsum dolor sit amet, impetus iuvaret in nam. Inani tritani fierent ut vix, vim ut dolore animal. Nisl noster fabellas sed ei.',
                    new Date('2022-04-21T19:36:01')),
                new Tweet(
                    'jdoe',
                    'John Doe',
                    'You can\'t stay in your corner of the Forest waiting for others to come to you. You have to go to them sometimes.',
                    new Date('2022-04-21T18:05:27'))
            ]
        };
    }

    render() {
        return (
            <Home>
                <Tweets tweets={this.state.tweets}/>
            </Home>
        );
    }
}
