// twitter-emulation-spring-boot-angular-web/src/app/modules/home/following.component.ts
import { Component, Inject } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Observer } from 'rxjs';
import { HomeAccountComponent } from './home-account.component';
import { AuthenticationService } from '../../shared/services/authentication.service';
import { FollowerService } from '../../shared/services/follower.service';
import { USER_STATE, UserState } from '../../shared/models/user-state.model';

@Component({
    selector: 'app-following',
    templateUrl: './home-account.component.html',
    standalone: false
})
export class FollowingComponent extends HomeAccountComponent {
  constructor(authenticationService: AuthenticationService, activatedRoute: ActivatedRoute, router: Router,
              @Inject(USER_STATE) observer: Observer<UserState>, private followerService: FollowerService) {
    super(authenticationService, activatedRoute, router, observer);

    this.title = 'Following';
  }

  getData(username: string) {
    this.followerService.getFollowing(username)
      .subscribe(data => {
        this.accounts = data;
      });
  }
}

// twitter-emulation-spring-boot-react-web/src/home/Following.tsx
import React, { Component } from 'react';
import { resolve } from 'inversify-react';
import ReactUtils from '../common/ReactUtils';
import { Account } from '../common/models/Account';
import { FollowerService } from '../common/services/FollowerService';
import AccountList from './AccountList';
import Home from './Home';

type FollowingProps = {
    params: any;
};

type FollowingState = {
    accounts: Account[];
};

class Following extends Component<FollowingProps, FollowingState> {
    @resolve(FollowerService)
    private readonly followerService!: FollowerService;

    constructor(props: FollowingProps) {
        super(props);

        this.state = {
            accounts: []
        };
    }

    componentDidMount() {
        const {user} = this.props.params;

        this.followerService.getFollowing(user)
            .subscribe(data => {
                this.setState({
                    accounts: data
                });
            });
    }

    render() {
        const {user} = this.props.params;

        return (
            <Home username={user}>
                <AccountList title={'Following'} accounts={this.state.accounts}></AccountList>
            </Home>
        );
    }
}

export default ReactUtils.withParams(Following);
