// twitter-emulation-spring-boot-angular-web/src/app/modules/home/home.component.ts
import { Component, Inject, OnInit } from '@angular/core';
import { Observable } from "rxjs";
import { AccountStatistics } from "../../shared/models/account-statistics.model";
import { AccountService } from "../../shared/services/account.service";
import { USER_STATE, UserState } from "../../shared/models/user-state.model";

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html'
})
export class HomeComponent implements OnInit {
  public userState: UserState = new UserState();
  public accountStatistics: AccountStatistics = new AccountStatistics();

  constructor(protected accountService: AccountService, @Inject(USER_STATE) private userStateObservable: Observable<UserState>) {
  }

  ngOnInit(): void {
    this.userStateObservable.subscribe((userState) => {
      this.userState = userState;
      const dataUserName = userState.getDataUserName();

      this.accountService.getAccountStatistics(dataUserName)
        .subscribe(data => {
          this.accountStatistics = data;
        });
    });
  }
}

<div class="container p-0">
  <div class="row m-0">
    <div class="col-12 mt-1">
      <app-message [autoHide]="true"></app-message>
    </div>
  </div>
  <app-top-bar [userState]="userState"></app-top-bar>
  <div class="row text-black m-0">
    <div class="col-3 p-1">
      <app-account-info [userState]="userState" [accountStatistics]="accountStatistics"></app-account-info>
    </div>
    <div class="col-6 p-1">
      <ng-content></ng-content>
    </div>
    <div class="col-3 p-1">
      <app-follow [userState]="userState" [accountStatistics]="accountStatistics"></app-follow>
    </div>
  </div>
</div>

// twitter-emulation-spring-boot-react-web/src/home/Home.tsx
import React, { Component } from 'react';
import AccountInfo from './AccountInfo';
import StatusInfo from './StatusInfo';
import TopBar from './TopBar';
import MessageText from '../message/MessageText';
import { AccountStatistics } from '../common/models/AccountStatistics';
import { UserState } from '../common/models/UserState';
import { AccountDataSource } from '../common/datasources/AccountDataSource';
import { resolve } from "inversify-react";

type HomeProps = {
    userState: UserState;
    children: React.ReactNode;
};

type HomeState = {
    accountStatistics: AccountStatistics;
};

export default class Home extends Component<HomeProps, HomeState> {
    @resolve(AccountDataSource)
    private readonly accountDataSource!: AccountDataSource;

    constructor(props: HomeProps) {
        super(props);

        // TODO: change
        this.state = {
            accountStatistics: new AccountStatistics()
        };
    }

    componentDidMount() {
        const dataUserName = this.props.userState.getDataUserName();

        if (dataUserName) {
            this.accountDataSource.getAccountStatistics(dataUserName)
                .subscribe(response => {
                    this.setState({accountStatistics: response.data});
                });
        }
    }

    render() {
        return (
            <div className="container p-0">
                <div className="row m-0">
                    <div className="col-12 mt-1">
                        <MessageText autoHide={true}></MessageText>
                    </div>
                </div>
                <TopBar userState={this.props.userState}/>
                <div className="row text-black m-0">
                    <div className="col-3 p-1">
                        <AccountInfo userState={this.props.userState} accountStatistics={this.state.accountStatistics}/>
                    </div>
                    <div className="col-6 p-1">
                        {this.props.children}
                    </div>
                    <div className="col-3 p-1">
                        <StatusInfo userState={this.props.userState}/>
                    </div>
                </div>
            </div>
        );
    }
}
