// twitter-emulation-spring-boot-angular-web/src/app/modules/home/status-info.component.ts
import { Component, Input } from '@angular/core';
import { UserState } from "../../shared/models/user-state.model";

@Component({
  selector: 'app-status-info',
  templateUrl: './status-info.component.html'
})
export class StatusInfoComponent {
  @Input('userState')
  userState: UserState;

  public copyrightDate = new Date();

  constructor() {
  }

  isStateVisible(): boolean {
    return this.userState.isAuthenticated();
  }
}

<div class="card p-3 bg-light">
  <div *ngIf="isStateVisible()" class="row m-1" id="state">
    <div class="col">
      Logged in as <span class="fw-bold">{{userState.authenticatedUserName}}</span>
    </div>
  </div>
  <div class="row m-1">
    <div class="col">
      &copy; Acme, {{copyrightDate | date:"yyyy"}}
    </div>
  </div>
</div>

// twitter-emulation-spring-boot-react-web/src/home/StatusInfo.tsx
import { Component } from 'react';
import { format } from 'date-fns';
import { UserState } from '../common/models/UserState';

type StatusInfoProps = {
    userState: UserState;
};

type StatusInfoState = {
    copyrightDate: Date;
};

export default class StatusInfo extends Component<StatusInfoProps, StatusInfoState> {
    constructor(props: StatusInfoProps) {
        super(props);

        // TODO: change
        this.state = {
            copyrightDate: new Date()
        };
    }

    isStateVisible(): boolean {
        return this.props.userState.isAuthenticated();
    }

    render() {
        return (
            <div className="card p-3 bg-light">
                <div className="row m-1" id="state">
                    <div className="col">
                        Logged in as <span className="fw-bold">{this.props.userState.authenticatedUserName}</span>
                    </div>
                </div>
                <div className="row m-1">
                    <div className="col">
                        &copy; Acme, {this.state.copyrightDate && format(this.state.copyrightDate, 'yyyy')}
                    </div>
                </div>
            </div>
        );
    }
}
