// twitter-emulation-spring-boot-angular-web/src/app/modules/unknown/not-found.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-not-found',
  templateUrl: './not-found.component.html'
})
export class NotFoundComponent {
}

<div class="container-dialog p-2">
  <h3 class="bg-info p-1 text-white text-center rounded">Page not found</h3>

  <div class="text-center">
    Go to <a routerLink="/account/show">Main page</a>
  </div>
</div>

// twitter-emulation-spring-boot-react-web2/src/unknown/NotFoundComponent.tsx
import { Component } from 'react';
import { Link } from 'react-router-dom';

export default class NotFoundComponent extends Component {
    render() {
        return (
            <div className="container-dialog p-2">
                <h3 className="bg-info p-1 text-white text-center rounded">Page not found</h3>

                <div className="text-center">
                    Go to <Link to="/account/show">Main page</Link>
                </div>
            </div>
        );
    }
}
