// twitter-emulation-spring-boot-angular-web/src/app/profile.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html'
})
export class ProfileComponent implements OnInit {
  credentials = {username: '', password: '', confirmation: '', description: ''};

  constructor() {
  }

  ngOnInit() {
  }

  save() {
    //TODO: implement
  }
}

<div class="container p-2">
  <h3 class="bg-info p-1 text-white text-center">Profile</h3>

  <form role="form" (submit)="save()">
    <div class="form-group">
      <label for="username">Username:</label>
      <input type="text"
             class="form-control" id="username" name="username"
             [(ngModel)]="credentials.username"/>
    </div>
    <div class="form-group">
      <label for="password">Password:</label>
      <input type="password"
             class="form-control" id="password" name="password"
             [(ngModel)]="credentials.password"/>
    </div>
    <div class="form-group">
      <label for="confirmation">Confirmation:</label>
      <input type="password"
             class="form-control" id="confirmation" name="confirmation"
             [(ngModel)]="credentials.confirmation"/>
    </div>
    <div class="form-group">
      <label for="description">Description:</label>
      <input type="text"
             class="form-control" id="description" name="description"
             [(ngModel)]="credentials.description"/>
    </div>
    <div class="text-center">
      <button type="submit" class="btn btn-primary m-1">Save</button>
      <button class="btn btn-secondary m-1" routerLink="/account/show">Cancel</button>
      <button class="btn btn-link m-1" routerLink="/account/delete">Delete</button>
    </div>
  </form>
</div>

// twitter-emulation-spring-boot-react-web/src/profile/Profile.tsx
import React, { ChangeEvent, Component } from 'react';
import { Link, Navigate } from 'react-router-dom';
import { resolve } from 'inversify-react';
import { FormValidator } from '../common/validation/FormValidator';
import { ValidatableInput } from '../common/validation/ValidatableInput';
import { ValidationMessages } from '../common/validation/ValidationMessages';
import { AccountService } from '../common/services/AccountService';
import { AuthenticationService } from '../common/services/AuthenticationService';
import NonValidationMessageText from '../message/NonValidationMessageText';

type ProfileProps = {};

type ProfileState = {
    username: string;
    password: string;
    confirmation: string;
    description: string;
    isSubmit: boolean;
};

export default class Profile extends Component<ProfileProps, ProfileState> {
    @resolve(AuthenticationService)
    private readonly authenticationService!: AuthenticationService;

    @resolve(AccountService)
    private readonly accountService!: AccountService;

    private readonly rules: any;

    constructor(props: ProfileProps) {
        super(props);

        this.state = {
            username: '',
            password: '',
            confirmation: '',
            description: '',
            isSubmit: false
        };

        this.rules = {
            username: {required: true, minlength: 1, maxlength: 16},
            password: {required: true, minlength: 5, maxlength: 25},
            confirmation: {required: true, minlength: 5, maxlength: 25, equals: 'password'},
            description: {required: true, minlength: 2, maxlength: 30}
        };
    }

    updateFormValue = (event: ChangeEvent<HTMLInputElement>) => {
        this.setState(prevState => ({
            ...prevState,
            [event.target.name]: event.target.value
        }));
    }

    submit = (data: any) => {
        // TODO: implement
        this.setState({
            isSubmit: true
        });
    }

    render() {
        return (
            <>
                {this.state.isSubmit ? <Navigate to={`/account/show/${this.state.username}`}/> :
                    <div className="container-dialog p-2">
                        <h3 className="bg-info p-1 text-white text-center rounded">Profile</h3>
                        <FormValidator data={this.state} rules={this.rules}
                                       submit={this.submit} submitButtonTitle={'Save'}
                                       rightButtons={
                                           <>
                                               <Link to="/account/show">
                                                   <button className="btn btn-secondary m-1" id="register">Cancel</button>
                                               </Link>
                                               <Link to="/account/delete">
                                                   <button className="btn btn-link m-1" id="register">Delete</button>
                                               </Link>
                                           </>}>
                            <NonValidationMessageText/>
                            <ValidationMessages/>

                            <div className="mb-3">
                                <label htmlFor="username" className="form-label">Username:</label>
                                <ValidatableInput type="text"
                                                  className="form-control" id="username" name="username"
                                                  value={this.state.username}
                                                  onChange={this.updateFormValue}
                                                  readOnly={true}/>
                            </div>
                            <div className="mb-3">
                                <label htmlFor="password" className="form-label">Password:</label>
                                <ValidatableInput type="password"
                                                  className="form-control" id="password" name="password"
                                                  value={this.state.password}
                                                  onChange={this.updateFormValue}/>
                            </div>
                            <div className="mb-3">
                                <label htmlFor="confirmation" className="form-label">Confirmation:</label>
                                <ValidatableInput type="password"
                                                  className="form-control" id="confirmation" name="confirmation"
                                                  value={this.state.confirmation}
                                                  onChange={this.updateFormValue}/>
                            </div>
                            <div className="mb-3">
                                <label htmlFor="description" className="form-label">Description:</label>
                                <ValidatableInput type="text"
                                                  className="form-control" id="description" name="description"
                                                  value={this.state.description}
                                                  onChange={this.updateFormValue}/>
                            </div>
                        </FormValidator>
                    </div>
                }
            </>
        );
    }
}
