// twitter-emulation-spring-boot-react-web2/src/registration/Registration.tsx
import React, { ChangeEvent, Component } from 'react';
import { Link, Navigate } from 'react-router-dom';
import { resolve } from 'inversify-react';
import { FormValidator } from '../common/validation/FormValidator';
import { ValidatableInput } from '../common/validation/ValidatableInput';
import { ValidationMessages } from '../common/validation/ValidationMessages';
import { AccountService } from '../common/services/AccountService';
import { Account } from '../common/models/Account';
import NonValidationMessageText from '../message/NonValidationMessageText';

type RegistrationProps = {};

type RegistrationState = {
    username: string;
    password: string;
    confirmation: string;
    description: string;
    isSubmit: boolean;
};

export default class Registration extends Component<RegistrationProps, RegistrationState> {
    @resolve(AccountService)
    private readonly accountService!: AccountService;

    private readonly rules: any;

    constructor(props: RegistrationProps) {
        super(props);

        this.state = {
            username: '',
            password: '',
            confirmation: '',
            description: '',
            isSubmit: false
        };

        this.rules = {
            username: {required: true, minlength: 1, maxlength: 16},
            password: {required: true, minlength: 5, maxlength: 25},
            confirmation: {required: true, minlength: 5, maxlength: 25, equals: 'password'},
            description: {required: true, minlength: 2, maxlength: 30}
        };
    }

    updateFormValue = (event: ChangeEvent<HTMLInputElement>) => {
        this.setState(prevState => ({
            ...prevState,
            [event.target.name]: event.target.value
        }));
    };

    submit = (data: any) => {
        this.accountService.addAccount(
            new Account(
                undefined,
                this.state.username,
                this.state.password,
                this.state.description),
            () => {
                this.setState({
                    isSubmit: true
                });
            });
    };

    render() {
        return (
            <>
                {this.state.isSubmit ? <Navigate to="/login"/> :
                    <div className="container-dialog p-2">
                        <h3 className="bg-info p-1 text-white text-center rounded">Registration</h3>

                        <FormValidator data={this.state} rules={this.rules}
                                       submit={this.submit} submitButtonTitle={'Register'}
                                       rightButtons={
                                           <Link to="/login">
                                               <button className="btn btn-link m-1" id="register">Log in</button>
                                           </Link>}>
                            <NonValidationMessageText/>
                            <ValidationMessages/>

                            <div className="mb-3">
                                <label htmlFor="username" className="form-label">Username:</label>
                                <ValidatableInput type="text"
                                                  className="form-control" id="username" name="username"
                                                  value={this.state.username}
                                                  onChange={this.updateFormValue}
                                                  autoFocus={true}/>
                            </div>
                            <div className="mb-3">
                                <label htmlFor="password" className="form-label">Password:</label>
                                <ValidatableInput type="password"
                                                  className="form-control" id="password" name="password"
                                                  value={this.state.password}
                                                  onChange={this.updateFormValue}/>
                            </div>
                            <div className="mb-3">
                                <label htmlFor="confirmation" className="form-label">Confirmation:</label>
                                <ValidatableInput type="password"
                                                  className="form-control" id="confirmation" name="confirmation"
                                                  value={this.state.confirmation}
                                                  onChange={this.updateFormValue}/>
                            </div>
                            <div className="mb-3">
                                <label htmlFor="description" className="form-label">Description:</label>
                                <ValidatableInput type="text"
                                                  className="form-control" id="description" name="description"
                                                  value={this.state.description}
                                                  onChange={this.updateFormValue}/>
                            </div>
                        </FormValidator>
                    </div>
                }
            </>
        );
    }
}

// twitter-emulation-spring-boot-angular-web/src/app/modules/registration/registration.component.ts
import { Component } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Router } from '@angular/router';
import { Account } from '../../shared/models/account.model';
import { AccountService } from '../../shared/services/account.service';

@Component({
  selector: 'app-registration',
  templateUrl: './registration.component.html'
})
export class RegistrationComponent {
  public formSubmitted: boolean = false;
  public credentials = {id: undefined, username: '', password: '', confirmation: '', description: ''};

  constructor(private accountService: AccountService, private router: Router) {
  }

  submitForm(form: NgForm) {
    this.formSubmitted = true;

    if (form.valid) {
      this.accountService.addAccount(
        new Account(
          this.credentials.id,
          this.credentials.username,
          this.credentials.password,
          this.credentials.description))
        .subscribe(data => {
          this.router.navigateByUrl('/login');
        });
    }
  }
}

<div class="container-dialog p-2">
  <h3 class="bg-info p-1 text-white text-center rounded">Registration</h3>

  <form novalidate #form="ngForm">
    <app-non-validation-message [isFormSubmitted]="formSubmitted" [isFormValid]="form.invalid"></app-non-validation-message>
    <app-validation-messages [isFormSubmitted]="formSubmitted" [form]="form"></app-validation-messages>

    <div class="mb-3">
      <label for="username" class="form-label">Username:</label>
      <input type="text"
             class="form-control" id="username" name="username"
             [(ngModel)]="credentials.username"
             required minlength="1" maxlength="16"
             appAutofocus/>
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password:</label>
      <input type="password"
             class="form-control" id="password" name="password"
             [(ngModel)]="credentials.password"
             required minlength="5" maxlength="25"/>
    </div>
    <div class="mb-3">
      <label for="confirmation" class="form-label">Confirmation:</label>
      <input type="password"
             class="form-control" id="confirmation" name="confirmation"
             [(ngModel)]="credentials.confirmation"
             required minlength="5" maxlength="25" appValidateEqual="password"/>
    </div>
    <div class="mb-3">
      <label for="description" class="form-label">Description:</label>
      <input type="text"
             class="form-control" id="description" name="description"
             [(ngModel)]="credentials.description"
             required minlength="2" maxlength="30"/>
    </div>
    <div class="text-center">
      <button type="submit" class="btn btn-primary m-1"
              [disabled]="formSubmitted && form.invalid"
              [class.btn-secondary]="formSubmitted && form.invalid"
              (click)="submitForm(form)">
        Register
      </button>
      <button class="btn btn-link m-1" routerLink="/login" id="login">Log in</button>
    </div>
  </form>
</div>
