// twitter-emulation-spring-boot-angular-web/src/app/new-tweet.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-new-tweet',
  templateUrl: './new-tweet.component.html'
})
export class NewTweetComponent implements OnInit {
  constructor() {
  }

  ngOnInit() {
  }

  tweet() {
    //TODO: implement
  }
}

<div>
  <h3 class="bg-info p-1 text-white">New tweet</h3>
</div>

// twitter-emulation-spring-boot-react-web/src/tweet/NewTweet.tsx
import { Component } from 'react';

export default class NewTweet extends Component {
    // TODO: implement
    render() {
        return (
            <div className="container-dialog p-2">
                <h3 className="bg-info p-1 text-white text-center rounded">New tweet</h3>
            </div>
        );
    }
}
