// twitter-emulation-spring-boot-angular-web/src/app/modules/tweet/new-tweet.component.ts
import { Component } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Router } from '@angular/router';
import { TweetService } from '../../shared/services/tweet.service';

@Component({
  selector: 'app-new-tweet',
  templateUrl: './new-tweet.component.html'
})
export class NewTweetComponent {
  public formSubmitted: boolean = false;
  public text: string;

  constructor(private tweetService: TweetService, private router: Router) {
  }

  submitForm(form: NgForm) {
    this.formSubmitted = true;

    if (form.valid) {
      this.tweetService.tweet(this.text)
        .subscribe(data => {
          this.router.navigateByUrl('/account/show');
        });
    }
  }
}

<div class="container-dialog p-2">
  <h3 class="bg-info p-1 text-white text-center rounded">New tweet</h3>

  <form novalidate #form="ngForm">
    <app-non-validation-message [isFormSubmitted]="formSubmitted" [isFormValid]="form.invalid"></app-non-validation-message>

    <div class="alert alert-danger"
         *ngIf="formSubmitted && form.invalid">
      There are problems with the form
      <ul>
        <li *ngFor="let error of getFormValidationMessages(form)">
          {{error}}
        </li>
      </ul>
    </div>

    <div class="mb-3">
      <textarea class="form-control" rows="3"
                id="text" name="text"
                [(ngModel)]="text"
                required minlength="1" maxlength="140"
                appAutofocus>
      </textarea>
    </div>
    <div class="text-center">
      <button type="submit" class="btn btn-primary m-1"
              [disabled]="formSubmitted && form.invalid"
              [class.btn-secondary]="formSubmitted && form.invalid"
              (click)="submitForm(form)">
        Tweet
      </button>
      <button class="btn btn-secondary m-1" routerLink="/account/show">Cancel</button>
    </div>
  </form>
</div>

// twitter-emulation-spring-boot-react-web/src/tweet/NewTweet.tsx
import React, { ChangeEvent, Component } from 'react';
import { Link, Navigate } from 'react-router-dom';
import { resolve } from 'inversify-react';
import { FormValidator } from '../common/validation/FormValidator';
import { ValidationMessages } from '../common/validation/ValidationMessages';
import { ValidatableTextarea } from '../common/validation/ValidatableTextarea';
import { TweetService } from '../common/services/TweetService';
import NonValidationMessageText from '../message/NonValidationMessageText';


type NewTweetProps = {};

type NewTweetState = {
    text: string;
    isSubmit: boolean;
}

export default class NewTweet extends Component<NewTweetProps, NewTweetState> {
    @resolve(TweetService)
    private readonly tweetService!: TweetService;

    private readonly rules: any;

    constructor(props: NewTweetProps) {
        super(props);

        this.state = {
            text: '',
            isSubmit: false
        };

        this.rules = {
            text: {required: true, minlength: 1, maxlength: 140},
        };
    }

    updateFormValue = (event: ChangeEvent<HTMLInputElement>) => {
        this.setState(prevState => ({
            ...prevState,
            [event.target.name]: event.target.value
        }));
    }

    submit = (data: any) => {
        this.tweetService.tweet(this.state.text)
            .subscribe(data => {
                this.setState({
                    isSubmit: true
                });
            });
    }

    render() {
        return (
            <>
                {this.state.isSubmit ? <Navigate to="/account/show"/> :
                    <div className="container-dialog p-2">
                        <h3 className="bg-info p-1 text-white text-center rounded">New tweet</h3>

                        <FormValidator data={this.state} rules={this.rules}
                                       submit={this.submit} submitButtonTitle={'Tweet'}
                                       rightButtons={
                                           <Link to="/account/show">
                                               <button className="btn btn-secondary m-1" id="register">Cancel</button>
                                           </Link>}>
                            <NonValidationMessageText/>
                            <ValidationMessages/>

                            <div className="mb-3">
                                <ValidatableTextarea className="form-control" rows={3} id="text" name="text"
                                                     value={this.state.text} onChange={this.updateFormValue}
                                                     autoFocus={true}/>
                            </div>
                        </FormValidator>
                    </div>
                }
            </>
        );
    }
}
