// twitter-emulation-spring-boot-react-web/src/home/Follow.tsx
import { Component } from "react";
import { format } from "date-fns";

type FollowProps = {};

type FollowState = {
    copyrightDate: Date;
};

export default class Follow extends Component<FollowProps, FollowState> {
    constructor(props: FollowProps) {
        super(props);

        // TODO: change
        this.state = {
            copyrightDate: new Date()
        };
    }

    render() {
        return (
            <div className="card p-3 bg-light">
                <div className="row m-1">
                    &copy; Acme, {this.state.copyrightDate && format(this.state.copyrightDate, 'yyyy')}
                </div>
            </div>
        );
    }
}

// twitter-emulation-spring-boot-angular-web/src/app/modules/home/follow.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { UserState } from "../../shared/models/user-state.model";
import { Account } from "../../shared/models/account.model";

@Component({
  selector: 'app-follow',
  templateUrl: './follow.component.html'
})
export class FollowComponent implements OnInit {
  @Input('userState')
  userState: UserState;

  @Input('account')
  account: Account;

  private isFollowVisible = false;
  private copyrightDate = new Date();

  constructor() {
  }

  ngOnInit() {
    //TODO: change
    this.isFollowVisible = this.userState.isAuthenticated() && (this.userState.authenticatedUserName !== this.userState.selectedUserName);
  }

  follow() {
    //TODO: implement
  }

  unfollow() {
    //TODO: implement
  }
}

<div class="card p-3 bg-light">
  <div *ngIf="isFollowVisible()" class="row m-1" id="buttons">
    <button *ngIf="!accountStatistics.follow" class="btn btn-primary m-0" (click)="follow()" id="follow">Follow</button>
    <button *ngIf="accountStatistics.follow" class="btn btn-primary m-0" (click)="unfollow()" id="unfollow">Unfollow</button>
  </div>
  <div *ngIf="isStateVisible()" class="row m-1" id="state">
    <div class="col">
      Logged in as <span class="fw-bold">{{userState.authenticatedUserName}}</span>
    </div>
  </div>
  <div class="row m-1">
    <div class="col">
      &copy; Acme, {{copyrightDate | date:"yyyy"}}
    </div>
  </div>
</div>
