// twitter-emulation-spring-boot-react-web/src/home/Followers.tsx
import React, { Component } from 'react';
import { resolve } from 'inversify-react';
import ReactUtils from '../common/ReactUtils';
import { Account } from '../common/models/Account';
import { FollowerDataSource } from '../common/datasources/FollowerDataSource';
import AccountList from './AccountList';
import Home from './Home';

type FollowersProps = {
    params: any;
};

type FollowersState = {
    accounts: Account[];
};

class Followers extends Component<FollowersProps, FollowersState> {
    @resolve(FollowerDataSource)
    private readonly followerDataSource!: FollowerDataSource;

    constructor(props: FollowersProps) {
        super(props);

        this.state = {
            accounts: []
        };
    }

    componentDidMount() {
        const {user} = this.props.params;

        this.followerDataSource.getFollowers(user)
            .subscribe(response => {
                this.setState({
                    accounts: response.data
                });
            });
    }

    render() {
        const {user} = this.props.params;

        return (
            <Home username={user}>
                <AccountList title={'Followers'} accounts={this.state.accounts}></AccountList>
            </Home>
        );
    }
}

export default ReactUtils.withParams(Followers);

// twitter-emulation-spring-boot-angular-web/src/app/modules/home/followers.component.ts
import { Component, Inject } from '@angular/core';
import { ActivatedRoute, Router } from "@angular/router";
import { Observer } from "rxjs";
import { HomeAccountComponent } from "./home-account.component";
import { AuthenticationService } from "../../shared/services/authentication.service";
import { FollowerService } from "../../shared/services/follower.service";
import { USER_STATE, UserState } from "../../shared/models/user-state.model";

@Component({
  selector: 'app-followers',
  templateUrl: './home-account.component.html'
})
export class FollowersComponent extends HomeAccountComponent {
  constructor(authenticationService: AuthenticationService, activatedRoute: ActivatedRoute, router: Router,
              @Inject(USER_STATE) observer: Observer<UserState>, private followerService: FollowerService) {
    super(authenticationService, activatedRoute, router, observer);

    this.title = 'Followers';
  }

  getData(username: string) {
    this.followerService.getFollowers(username)
      .subscribe(data => {
        this.accounts = data;
      });
  }
}
