// twitter-emulation-spring-boot-react-web/src/home/AccountInfo.tsx
import { Component } from 'react';
import { Link } from 'react-router-dom';
import { AccountStatistics } from '../common/models/AccountStatistics';
import { UserState } from '../common/models/UserState';

type AccountInfoProps = {
    userState: UserState;
    accountStatistics: AccountStatistics;
};

type AccountInfoState = {};

export default class AccountInfo extends Component<AccountInfoProps, AccountInfoState> {
    render() {
        return (
            <div className="card p-3 bg-light">
                <div className="row fw-bold">
                    <div className="col-12" id="description">
                        {this.props.accountStatistics.description}
                    </div>
                </div>
                <div className="row">
                    <div className="col-12" id="username">
                        @{this.props.accountStatistics.username}
                    </div>
                </div>
                <div className="row mt-1">
                    <div className="col-4 small">
                        <Link to={`/account/tweets/${this.props.accountStatistics.username}`} className="fw-bold">
                            Tweets
                        </Link>
                    </div>
                    <div className="col-4 small">
                        <Link to={`/account/following/${this.props.accountStatistics.username}`} className="fw-bold">
                            Following
                        </Link>
                    </div>
                    <div className="col-4 small">
                        <Link to={`/account/followers/${this.props.accountStatistics.username}`} className="fw-bold">
                            Followers
                        </Link>
                    </div>
                </div>
                <div className="row">
                    <div className="col-4 small">
                        <Link to={`/account/tweets/${this.props.accountStatistics.username}`} className="fw-bold">
                            {this.props.accountStatistics.tweetsCount}
                        </Link>
                    </div>
                    <div className="col-4 small">
                        <Link to={`/account/following/${this.props.accountStatistics.username}`} className="fw-bold">
                            {this.props.accountStatistics.followingCount}
                        </Link>
                    </div>
                    <div className="col-4 small">
                        <Link to={`/account/followers/${this.props.accountStatistics.username}`} className="fw-bold">
                            {this.props.accountStatistics.followersCount}
                        </Link>
                    </div>
                </div>
            </div>
        );
    }
}

// twitter-emulation-spring-boot-angular-web/src/app/home/account-info.component.ts
import { Component, OnInit } from '@angular/core';

export class Account {
  constructor(
    public username?: string,
    public description?: string
  ) {
  }
}

export class AccountStatistics {
  constructor(
    public tweetsCount?: number,
    public followingCount?: number,
    public followersCount?: number
  ) {
  }
}

@Component({
  selector: 'app-account-info',
  templateUrl: './account-info.component.html'
})
export class AccountInfoComponent implements OnInit {
  private account: Account = new Account('jsmith', 'John Smith');
  private accountStatistics: AccountStatistics = new AccountStatistics(6, 2, 1);

  constructor() {
  }

  ngOnInit() {
  }
}

<div class="card p-3 bg-light">
  <table class="w-100">
    <tr>
      <td colspan="3" class="font-weight-bold">
        {{account.description}}
      </td>
    </tr>
    <tr>
      <td colspan="3">
        @{{account.username}}
      </td>
    </tr>
    <tr>
      <td class="small"><a class="font-weight-bold" href="#">Tweets</a></td>
      <td class="small"><a class="font-weight-bold" href="#">Following</a></td>
      <td class="small"><a class="font-weight-bold" href="#">Followers</a></td>
    </tr>
    <tr>
      <td class="small"><a class="font-weight-bold" href="#">{{accountStatistics.tweetsCount}}</a></td>
      <td class="small"><a class="font-weight-bold" href="#">{{accountStatistics.followingCount}}</a></td>
      <td class="small"><a class="font-weight-bold" href="#">{{accountStatistics.followersCount}}</a></td>
    </tr>
  </table>
</div>
