// twitter-emulation-spring-boot-react-web/src/home/TopBar.tsx
import { Component } from "react";
import { Link } from "react-router-dom";

type TopBarProps = {};

type TopBarState = {};

export default class TopBar extends Component<TopBarProps, TopBarState> {
    logout() {
        //TODO: implement
        console.log('logout()');
    }

    render() {
        return (
            <div className="row m-0">
                <div className="col-3 p-1">
                    <Link to="/account/show" className="btn btn-link m-0" role="button">Main</Link>
                </div>
                <div className="col-6 p-1">
                    <div className="input-group mt-1">
                        <input type="search" className="form-control" id="searchText" name="searchText" placeholder="Search accounts..."/>
                        <div className="input-group-append">
                            <button className="btn btn-primary">Search</button>
                        </div>
                    </div>
                </div>
                <div className="col-3 p-1">
                    <Link to="/tweet">
                        <button className="btn btn-primary m-1">Tweet</button>
                    </Link>
                    <Link to="/account/profile">
                        <button className="btn btn-link m-1">Profile</button>
                    </Link>
                    <button className="btn btn-link m-1" onClick={this.logout}>Logout</button>
                </div>
            </div>
        );
    }
}

// twitter-emulation-spring-boot-angular-web/src/app/home/top-bar.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthenticationService } from "../authentication.service";
import { Router } from "@angular/router";

@Component({
  selector: 'app-top-bar',
  templateUrl: './top-bar.component.html'
})
export class TopBarComponent implements OnInit {
  constructor(private auth: AuthenticationService, private router: Router) {
  }

  ngOnInit() {
  }

  logout() {
    this.auth.logout(() => {
      this.router.navigate(['/login'], {
        queryParams: {
          "logout": true
        }
      });
    });
  }

  search() {
    //TODO: implement
  }
}

<div class="row m-0">
  <div class="col-3 p-1">
    <button class="btn btn-link m-1" routerLink="/account/show">Main</button>
  </div>
  <div class="col-6 p-1">
    <form role="form" class="form-inline" (submit)="search()">
      <input type="search" class="form-control" id="search" name="search" placeholder="Search accounts..."/>
      <button class="btn btn-primary m-1" routerLink="/account/search">Search</button>
    </form>
  </div>
  <div class="col-3 p-1">
    <button class="btn btn-primary m-1" routerLink="/tweet">Tweet</button>
    <button class="btn btn-link m-1" routerLink="/account/profile">Profile</button>
    <button class="btn btn-link m-1" (click)="logout()">Logout</button>
  </div>
</div>
