// twitter-emulation-spring-boot-angular-web/src/app/modules/home/tweets.component.ts
import { Component, Inject } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Observer } from 'rxjs';
import { HomeTweetsComponent } from './home-tweets.component';
import { AuthenticationService } from '../../shared/services/authentication.service';
import { TweetService } from '../../shared/services/tweet.service';
import { USER_STATE, UserState } from '../../shared/models/user-state.model';

@Component({
  selector: 'app-tweets',
  templateUrl: './home-tweets.component.html'
})
export class TweetsComponent extends HomeTweetsComponent {
  constructor(authenticationService: AuthenticationService, activatedRoute: ActivatedRoute, router: Router,
              @Inject(USER_STATE) observer: Observer<UserState>, private tweetService: TweetService) {
    super(authenticationService, activatedRoute, router, observer);

    this.title = 'Tweets';
  }

  getData(username: string) {
    this.tweetService.getTweets(username)
      .subscribe(data => {
        this.tweets = data;
      });
  }
}

// twitter-emulation-spring-boot-react-web2/src/home/Tweets.tsx
import { Component } from 'react';
import { resolve } from 'inversify-react';
import { Tweet } from '../common/models/Tweet';
import Home from './Home';
import TweetList from './TweetList';
import ReactUtils from '../common/ReactUtils';
import { TweetService } from '../common/services/TweetService';

type TweetsProps = {
    params: any;
};

type TweetsState = {
    tweets: Tweet[];
};

class Tweets extends Component<TweetsProps, TweetsState> {
    @resolve(TweetService)
    private readonly tweetService!: TweetService;

    constructor(props: TweetsProps) {
        super(props);

        this.state = {
            tweets: []
        };
    }

    componentDidMount() {
        const {user} = this.props.params;

        this.tweetService.getTweets(user, response => {
            this.setState({
                tweets: response.data
            });
        });
    }

    render() {
        const {user} = this.props.params;

        return (
            <Home username={user}>
                <TweetList title={'Tweets'} tweets={this.state.tweets}/>
            </Home>
        );
    }
}

export default ReactUtils.withParams(Tweets);
