// twitter-emulation-spring-boot-react-web/src/profile/DeleteAccount.tsx
import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useInjection } from 'inversify-react';
import { AccountService } from '../common/services/AccountService';
import { AuthenticationService } from '../common/services/AuthenticationService';
import { User } from '../common/models/User';
import MessageText from '../message/MessageText';

export default function DeleteAccount() {
    const [user, setUser] = useState<User>(new User());
    const authenticationService = useInjection(AuthenticationService);
    const accountService = useInjection(AccountService);
    const navigate = useNavigate();

    useEffect(() => {
        authenticationService.getUser()
            .subscribe(data => {
                setUser(data);
            });
    }, []);

    function deleteAccount() {
        if (user.name) {
            accountService.deleteAccount(user.name)
                .subscribe(() => {
                    navigate({
                        pathname: '/login',
                        search: '?logout=1'
                    });
                });
        }
    }

    return (
        <div className="container-dialog p-2">
            <h3 className="bg-danger p-1 text-white text-center rounded">Delete account</h3>

            <MessageText/>

            <div className="alert text-center">
                Are you sure to delete account '{user.name}'?
            </div>
            <div className="text-center">
                <button className="btn btn-danger m-1" onClick={deleteAccount}>Delete</button>
                <Link to="/account/profile">
                    <button className="btn btn-secondary m-1">Cancel</button>
                </Link>
            </div>
        </div>
    );
}

// twitter-emulation-spring-boot-angular-web/src/app/modules/profile/delete-account.component.ts
import { Component } from '@angular/core';
import { Router } from "@angular/router";
import { User } from "../../shared/models/user.model";
import { AuthenticationService } from "../../shared/services/authentication.service";
import { AccountService } from "../../shared/services/account.service";

@Component({
  selector: 'app-delete-account',
  templateUrl: './delete-account.component.html'
})
export class DeleteAccountComponent {
  public user: User = new User();

  constructor(private authenticationService: AuthenticationService, private accountService: AccountService, private router: Router) {
    authenticationService.getUser().subscribe(data => {
      this.user = data;
    });
  }

  delete() {
    this.accountService.deleteAccount(this.user.name)
      .subscribe(data => {
        this.router.navigate(['/login'], {
          queryParams: {
            "logout": 1
          }
        });
      });
  }
}

<div class="container-dialog p-2">
  <h3 class="bg-danger p-1 text-white text-center rounded">Delete account</h3>

  <app-message></app-message>

  <div class="alert text-center">
    Are you sure to delete account '{{user.name}}'?
  </div>
  <div class="text-center">
    <button class="btn btn-danger m-1" (click)="delete()">Delete</button>
    <button class="btn btn-secondary m-1" routerLink="/account/profile">Cancel</button>
  </div>
</div>
