// twitter-emulation-spring-boot-react-web/src/profile/Profile.tsx
import React, { ChangeEvent, Component } from 'react';
import { Link, Navigate } from 'react-router-dom';
import { resolve } from 'inversify-react';
import { FormValidator } from '../common/validation/FormValidator';
import { ValidatableInput } from '../common/validation/ValidatableInput';
import { ValidationMessages } from '../common/validation/ValidationMessages';
import { AccountService } from '../common/services/AccountService';
import { AuthenticationService } from '../common/services/AuthenticationService';
import NonValidationMessageText from '../message/NonValidationMessageText';
import { Account } from '../common/models/Account';

type ProfileProps = {};

type ProfileState = {
    id?: number,
    username: string;
    password: string;
    confirmation: string;
    description: string;
    isSubmit: boolean;
};

export default class Profile extends Component<ProfileProps, ProfileState> {
    @resolve(AuthenticationService)
    private readonly authenticationService!: AuthenticationService;

    @resolve(AccountService)
    private readonly accountService!: AccountService;

    private readonly rules: any;

    constructor(props: ProfileProps) {
        super(props);

        this.state = {
            id: undefined,
            username: '',
            password: '',
            confirmation: '',
            description: '',
            isSubmit: false
        };

        this.rules = {
            username: {required: true, minlength: 1, maxlength: 16},
            password: {required: true, minlength: 5, maxlength: 25},
            confirmation: {required: true, minlength: 5, maxlength: 25, equals: 'password'},
            description: {required: true, minlength: 2, maxlength: 30}
        };
    }

    updateFormValue = (event: ChangeEvent<HTMLInputElement>) => {
        this.setState(prevState => ({
            ...prevState,
            [event.target.name]: event.target.value
        }));
    }

    componentDidMount() {
        this.authenticationService.getUser()
            .subscribe(user => {
                if (user.name) {
                    this.accountService.getAccount(user.name)
                        .subscribe(account => {
                            this.setState({
                                id: account.id,
                                username: (account.username) ? account.username : '',
                                password: (account.password) ? account.password : '',
                                confirmation: (account.password) ? account.password : '',
                                description: (account.description) ? account.description : ''
                            });
                        });
                }
            });
    }

    submit = (data: any) => {
        this.accountService.saveAccount(
            this.state.username,
            new Account(
                this.state.id,
                this.state.username,
                this.state.password,
                this.state.description))
            .subscribe(data => {
                this.setState({
                    isSubmit: true
                });
            });
    }

    render() {
        return (
            <>
                {this.state.isSubmit ? <Navigate to={`/account/show/${this.state.username}`}/> :
                    <div className="container-dialog p-2">
                        <h3 className="bg-info p-1 text-white text-center rounded">Profile</h3>
                        <FormValidator data={this.state} rules={this.rules}
                                       submit={this.submit} submitButtonTitle={'Save'}
                                       rightButtons={
                                           <>
                                               <Link to="/account/show">
                                                   <button className="btn btn-secondary m-1" id="cancel">Cancel</button>
                                               </Link>
                                               <Link to="/account/delete">
                                                   <button className="btn btn-link m-1">Delete</button>
                                               </Link>
                                           </>}>
                            <NonValidationMessageText/>
                            <ValidationMessages/>

                            <div className="mb-3">
                                <label htmlFor="username" className="form-label">Username:</label>
                                <ValidatableInput type="text"
                                                  className="form-control" id="username" name="username"
                                                  value={this.state.username}
                                                  onChange={this.updateFormValue}
                                                  readOnly={true}/>
                            </div>
                            <div className="mb-3">
                                <label htmlFor="password" className="form-label">Password:</label>
                                <ValidatableInput type="password"
                                                  className="form-control" id="password" name="password"
                                                  value={this.state.password}
                                                  onChange={this.updateFormValue}/>
                            </div>
                            <div className="mb-3">
                                <label htmlFor="confirmation" className="form-label">Confirmation:</label>
                                <ValidatableInput type="password"
                                                  className="form-control" id="confirmation" name="confirmation"
                                                  value={this.state.confirmation}
                                                  onChange={this.updateFormValue}/>
                            </div>
                            <div className="mb-3">
                                <label htmlFor="description" className="form-label">Description:</label>
                                <ValidatableInput type="text"
                                                  className="form-control" id="description" name="description"
                                                  value={this.state.description}
                                                  onChange={this.updateFormValue}/>
                            </div>
                        </FormValidator>
                    </div>
                }
            </>
        );
    }
}

// twitter-emulation-spring-boot-angular-web/src/app/modules/profile/profile.component.ts
import { Component } from '@angular/core';
import { NgForm } from "@angular/forms";
import { Router } from "@angular/router";
import { Account } from "../../shared/models/account.model";
import { AuthenticationService } from "../../shared/services/authentication.service";
import { AccountService } from "../../shared/services/account.service";
import { ValidationService } from "../../shared/services/validation.service";
import { User } from "../../shared/models/user.model";

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html'
})
export class ProfileComponent {
  private formSubmitted: boolean = false;
  private credentials = {username: '', password: '', passwordConfirmation: '', description: ''};
  private user: User = new User();

  constructor(private authenticationService: AuthenticationService, private accountService: AccountService, private validationService: ValidationService, private router: Router) {
    authenticationService.getUser().subscribe(data => {
      this.user = data;

      accountService.getAccount(this.user.name).subscribe(data => {
        this.credentials.username = data.username;
        this.credentials.password = data.password;
        this.credentials.passwordConfirmation = data.password;
        this.credentials.description = data.description;
      });
    });
  }

  submitForm(form: NgForm) {
    this.formSubmitted = true;

    if (form.valid) {
      this.accountService.saveAccount(
        this.user.name,
        new Account(
          this.credentials.username,
          this.credentials.password,
          this.credentials.description)
      ).subscribe(data => {
        this.router.navigate(['/account', 'show', this.credentials.username]);
      });
    }
  }

  getFormValidationMessages(form: NgForm): string[] {
    return this.validationService.getFormValidationMessages(form);
  }
}

<div class="container-dialog p-2">
  <h3 class="bg-info p-1 text-white text-center rounded">Profile</h3>

  <form novalidate #form="ngForm">
    <app-non-validation-message [isFormSubmitted]="formSubmitted" [isFormValid]="form.invalid"></app-non-validation-message>

    <div class="alert alert-danger"
         *ngIf="formSubmitted && form.invalid">
      There are problems with the form
      <ul>
        <li *ngFor="let error of getFormValidationMessages(form)">
          {{error}}
        </li>
      </ul>
    </div>

    <div class="mb-3">
      <label for="username" class="form-label">Username:</label>
      <input type="text"
             class="form-control" id="username" name="username"
             [(ngModel)]="credentials.username" readonly
             required minlength="1" maxlength="16"/>
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password:</label>
      <input type="password"
             class="form-control" id="password" name="password"
             [(ngModel)]="credentials.password"
             required minlength="5" maxlength="25"/>
    </div>
    <div class="mb-3">
      <label for="confirmation" class="form-label">Confirmation:</label>
      <input type="password"
             class="form-control" id="confirmation" name="confirmation"
             [(ngModel)]="credentials.confirmation"
             required minlength="5" maxlength="25" appValidateEqual="password"/>
    </div>
    <div class="mb-3">
      <label for="description" class="form-label">Description:</label>
      <input type="text"
             class="form-control" id="description" name="description"
             [(ngModel)]="credentials.description"
             required minlength="2" maxlength="30"/>
    </div>
    <div class="text-center">
      <button type="submit" class="btn btn-primary m-1"
              [disabled]="formSubmitted && form.invalid"
              [class.btn-secondary]="formSubmitted && form.invalid"
              (click)="submitForm(form)">
        Save
      </button>
      <button class="btn btn-secondary m-1" routerLink="/account/show" id="cancel">Cancel</button>
      <button class="btn btn-link m-1" routerLink="/account/delete">Delete</button>
    </div>
  </form>
</div>
